### PR TITLE
Asm

### PR DESCRIPTION
**Pull request by patriciajklein**

### CODE REVIEW

**Comment by patriciajklein** [comment]
[Background.md](https://github.com/Macaulay2/Workshop-2023-Minneapolis/files/11511434/Background.md)

**Comment by patriciajklein** [comment]
Brief background and summary of goals for the Schubert/ASM package.

**Comment by mahrud** [comment]
Hi Tricia! You can directly push to `asm` (as you have been doing), and there's no need to merge the changes into `main` (which is only for stuff common to all projects). I'll close this so it doesn't get accidentally merged.

**Comment by patriciajklein** [comment]
Sorry, and thank you!

**Pull request closed without merging**
